### ISSUE TITLE
fastapi-jwt on pypi is still 0.1.8 and not 0.1.9

### ISSUE THREAD

**Issue by nsteinmetz** [k4black/fastapi-jwt#11]
Hi there,

Glad to see a new release with Python 3.11 support - but seems the release does not go up to pypi : https://pypi.org/project/fastapi-jwt/ is still on 0.1.8.

Despite the github-actions being in place, seems something did not work for the release.

Could you please review this and publish the latest package on pypi too ?

Thanks a lot !

**Comment by nsteinmetz** [comment]
Maybe an explaination : `VERSION` (https://github.com/k4black/fastapi-jwt/blob/main/VERSION) is still `0.1.8`

And installing 0.1.9 package is also seen as installing 0.1.8 version:

```
❯ poetry add https://github.com/k4black/fastapi-jwt/archive/refs/tags/0.1.9.tar.gz

Updating dependencies
Resolving dependencies... (7.9s)

Writing lock file

Package operations: 0 installs, 1 update, 0 removals

  • Updating fastapi-jwt (0.1.8 -> 0.1.8 https://github.com/k4black/fastapi-jwt/archive/refs/tags/0.1.9.tar.gz)
```

**Comment by k4black** [comment]
Thank you! Fixed!   
Now it's 0.1.12

**Comment by nsteinmetz** [comment]
You're welcome - glad it's fixed !
