### ISSUE TITLE
Bump supported python version?

### ISSUE THREAD

**Issue by farridav** [k4black/fastapi-jwt#4]
Im unable to install this project in my python 3.10 project, as you have pinned `>=3.7,<3.10` in setup.cfg

I think this code will probably run with 3.10

**Comment by smithk86** [comment]
I just opened a pull request to fix compatibility with Python 3.10. The only changes are removing the upper version limits for the three main dependencies (including Python), and adding 3.10 to the Github Test workflow.

All the tests are passing with Python 3.10.

For now, you can install it from my fork if you want to test it:
PIP: pip install git+https://github.com/smithk86/fastapi-jwt.git@7172c9dad57e2d35efad493acea85faa921a07cb
Poetry: poetry add git+https://github.com/smithk86/fastapi-jwt.git@7172c9dad57e2d35efad493acea85faa921a07cb

**Comment by lafrenierejm** [comment]
Looks like this was resolved by https://github.com/k4black/fastapi-jwt/pull/5.
