### ISSUE TITLE
How to refresh tokens?

### ISSUE THREAD

**Issue by Myzel394** [k4black/fastapi-jwt#8]
I'm currently trying to implement the refresh token functionality, but I always get the error:

```
Credentials are not provided
```

The request is made using `axios` with `withCredentials: true` enabled in the options.

Here's the code for the server:

```python
@router.post(
    "/refresh",
)
async def refresh_token(
    response: Response,
    credentials: JwtAuthorizationCredentials = Security(refresh_security),
    db: Session = Depends(get_db),
):
    logger.info("Request: Refresh -> New Request to refresh JWT token.")

    user = get_user_by_id(db, credentials["id"])

    logger.info("Request: Refresh -> Returning new credentials.")

    set_authentication_cookies(response, user)

    return {
        "user": user,
        "detail": "Token refreshed successfully!"
    }
```

**Comment by Sebsebzen** [comment]
It appears to be because it doesn't read the refresh_cookie (if you have set it up). Try submitting the refresh_token string directly by opening the refresh route in Swagger UI and clicking on the lock icon.

![image](https://user-images.githubusercontent.com/6603152/207379906-db9cfb7e-59d7-460d-ac85-8504917388d3.png)

**Comment by Myzel394** [comment]
@Sebsebzen Thanks for your answer. This does seem to do the trick, however I need to send the token via Axios. The refresh token is set up in a `httpOnly` cookie, so we can't read it. Is this an underlying problem with `fastapi-jwt` or am I doing something wrong?

**Comment by Sebsebzen** [comment]
I'm new to this library too, but it could be an underlying problem @k4black ? 

After all, there is a staticmethod to set the refresh cookie, so logically there should be a way to refresh with it.

**Comment by Sebsebzen** [comment]
@Myzel394 I found the solution. You need to setup `refresh_security` like this:

```
refresh_security = JwtRefreshBearerCookie(
    secret_key=SECRET_KEY, 
    auto_error=True  # automatically raise HTTPException: HTTP_401_UNAUTHORIZED 
)
```

use `JwtRefreshBearerCookie` to read access token from **both** bearer and cookie

**Comment by Sebsebzen** [comment]
I had the same problem, no worries :)
